---
title: "lab03-adele-shen"
output: html_document
---
What’s the character delimiter?
- comma
Is there a row for column names?
- no
Are there any missing values? If so, how are they codified?
- no
What is the data type of each column?
- character, real, real, ..., real, integer

```{r}
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
abalone <- read.table(url, sep = ",")

```

```{r}
origin <- 'http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data'
destination <- 'abalone.data'
download.file(origin, destination)
```

```{r}
abalone <- read.table("abalone.data", sep = ",")
```

```{r}
head(abalone)
tail(abalone)
```

```{r}
str(abalone, vec.len = 1)
```

```{r}
column_names = c("Sex", "Length", "Diameter", "Height", "Whole", "Shucked", "Viscera", "Shell", "Rings")
```

```{r}
column_types = c("character", "real", "real", "real", "real", "real", "real", "real", "integer")
```

```{r}
abalone = read.table( "abalone.data", sep = ",", col.names = column_names, colClasses = column_types)
```

```{r}
abalone2 = read.csv("abalone.data", header = FALSE, sep = ",", col.names = column_names, colClasses = column_types)
#if don't put header = FALSE even though you have headers from column_names, will consider first row of data as column names, then replace them with column_names, effectively deleting first row of data
```
```{r}
abalone10 = head(abalone, 10)
str(abalone)
```

```{r}
abalone20 = read.table("abalone.data", sep = ",", col.names = column_names, colClasses = column_types, nrows = 10, skip = 10)
str(abalone20)
```

```{r}
#Read the documentation of read.table() about the argument colClasses. What happens when you specify the data-type of one or more columns as "NULL"?

ccolumn_types = c("NULL", "real", "real", "real", "real", "real", "real", "real", "integer")
read.table("abalone.data", sep = ",", col.names = column_names, colClasses = ccolumn_types)

#The Column is just omitted from the table.
```

```{r}
str(abalone)
summary(abalone)
head(abalone)
tail(abalone)
dim(abalone)
names(abalone)
colnames(abalone)
nrow(abalone)
ncol(abalone)
```

```{r}
min = c(min(abalone$Length), min(abalone$Diameter), min(abalone$Height), min(abalone$Whole), min(abalone$Shucked), min(abalone$Viscera), min(abalone$Shell), min(abalone$Rings))
max = c(max(abalone$Length), max(abalone$Diameter), max(abalone$Height), max(abalone$Whole), max(abalone$Shucked), max(abalone$Viscera), max(abalone$Shell), max(abalone$Rings))
mean = c(mean(abalone$Length), mean(abalone$Diameter), mean(abalone$Height), mean(abalone$Whole), mean(abalone$Shucked), mean(abalone$Viscera), mean(abalone$Shell), mean(abalone$Rings))
sd = c(sd(abalone$Length), sd(abalone$Diameter), sd(abalone$Height), sd(abalone$Whole), sd(abalone$Shucked), sd(abalone$Viscera), sd(abalone$Shell), sd(abalone$Rings))
```

```{r}
mat = rbind(min, max, mean, sd)
colnames(mat) = c("Length", "Diameter", "Height", "Whole", "Shucked", "Viscera", "Shell", "Rings")
data.frame(mat)
```


## Filtering, Slicing, Selecting
```{r}
#slicing
three_rows <- abalone[1:3, ]
three_rows
```

```{r}
five_rows = abalone[1:5, ]
everyfiverows = abalone[seq(from = 5, to = nrow(abalone), by = 5), ]
everyfiverows
```

```{r}
lastfiverows = abalone[seq(from = nrow(abalone) - 4, to = nrow(abalone), by = 1), ]
```

```{r}
#filtering
#create a data frame height14 by filtering the data with those abalones with Height less than 0.14, and display its dimensions with dim()

height14 = data.frame(abalone[abalone$Height < 0.14, ])
dim(height14)
```

```{r}
#create a data frame infant by filtering the data about Infant abalones, and display its dimensions with dim()

infant = data.frame(abalone[abalone$Sex == "I", ])
dim(infant)
```

```{r}
#create a data frame male_female by filtering the data with Male and Female abalones, and display its dimensions with dim()

male_female = data.frame(abalone[abalone$Sex != "I", ])
dim(male_female)
#or
male_female2 = data.frame(abalone[abalone$Sex == "M" | abalone$Sex == "F", ])
dim(male_female2)
```

```{r}
#filter the data with those abalones with more than 25 Rings, displaying only their Sex, and Rings.

over25 = data.frame(abalone[abalone$Rings >= 25, c('Sex', 'Rings')])
over25

abalone[abalone$Rings >= 25, c('Sex', 'Rings')]
```


```{r}
#filter the data with those infant abalones with more than 3 Rings and less than 6, displaying only their Sex, Rings, and Diameter.

filter = abalone[abalone$Sex == "I" & abalone$Rings > 3 & abalone$Rings < 6, c('Sex', 'Rings', 'Diameter')]
filter
```

```{r}
#selecting
length_diam <- abalone[ ,c('Length', 'Diameter')]
head(length_diam)
```

##Adding new variables and Sorting rows
```{r}
# creating a small data frame
abies <- abalone[abalone$Sex == 'I', c('Length', 'Height', 'Diameter')]
```

```{r}
abies$Ht_Len <- abies$Height / abies$Length
abies2 <- abies[order(abies$Length, decreasing = TRUE), ]
```

```{r}
# using the data frame abies, add a new variable product with the product of Whole and Shucked.

abies$product = abalone$Whole[abalone$Sex == 'I']* abalone$Shucked[abalone$Sex == 'I']

```

```{r}
abies3 = abies
abies3$log_height = log(abies$Height)
abies3$log_length = log(abies$Length)
```

```{r}
abalone[order(abalone$Height < 0.12, decreasing = FALSE),]
```

```{r}
# display a data frame with the Sex, Diameter, and Rings, of the top-5 highest abalones
head(data.frame(abalone[order(abalone$Height, decreasing = TRUE), c('Sex', 'Diameter', 'Rings')]), 5)
```
           
```{r}
longest = order(abalone$Length, decreasing = TRUE)[1:5]
abalone[longest, c('Sex', 'Diameter', 'Rings')]
```

# Basic Plots
```{r}
plot(abalone$Height)
```

```{r}
plot(table(abalone$Sex))
```

```{r}
plot(abalone$Height, abalone$Length)
```
```{r}
plot(abalone[ ,c('Height', 'Length')])
```

```{r}
plot(abalone[ ,c('Height', 'Length', 'Diameter')])
```

```{r}
# a 2-column data frame with one factor in the first column, and one numeric vector in the second column: e.g. Sex and Length

# a 2-column data frame with one numeric vector in the first column, and one factor in the second column: e.g. Length and Sex
```
















